class StoryModel {
  final String imagePath;

  StoryModel({
    required this.imagePath,
  });
}

List<StoryModel> storyList = [
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
  StoryModel(
    imagePath:
        'https://img.freepik.com/premium-vector/lion-head-logo-generative-ai-golden-mane-zoo-high-detail-design-style-minimalism-avatar-work-success-career-character-job-wild-animals-concept-vector-illustration_748571-1000.jpg',
  ),
];
